install.packages('devtools')
library(devtools)
devtools::install_github('vqv/ggbiplot')
install.packages('packrat')

install.packages('shiny')
install.packages('shinydashboard')
install.packages('shinydashboardPlus')
install.packages('magrittr')
install.packages('xtable')
install.packages('plotly')
install.packages('utf8')
install.packages('FactoMineR')
install.packages('factoextra')
install.packages('tidyr')
install.packages('forecast')
install.packages('shinymanager')
install.packages('lubridate')
